CREATE SCHEMA `taskworld ` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
CREATE TABLE `taskworld`.`attacking_logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `result` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `game_state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT 'PROCESS',
  `hit_ship_id` VARCHAR(50) CHARACTER SET 'utf8',
  `hit_ship_type` VARCHAR(20) CHARACTER SET 'utf8',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

CREATE TABLE `taskworld`.`ships` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT 'FLOAT',
  `position_x` INT UNSIGNED NOT NULL,
  `position_y` INT UNSIGNED NOT NULL,
  `axis` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `position_state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `ship_id` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


CREATE SCHEMA `test ` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
CREATE TABLE `test`.`attacking_logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `result` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `game_state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT 'PROCESS',
  `hit_ship_id` VARCHAR(50) CHARACTER SET 'utf8',
  `hit_ship_type` VARCHAR(20) CHARACTER SET 'utf8',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

CREATE TABLE `test`.`ships` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT 'FLOAT',
  `position_x` INT UNSIGNED NOT NULL,
  `position_y` INT UNSIGNED NOT NULL,
  `axis` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `position_state` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `ship_id` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);